### ISSUE TITLE
No workflow for only SMS

### ISSUE THREAD

**Issue by anmol5varma** [Nexmo/nexmo-java-code-snippets#65] opened 2019-12-12 10:55 UTC
https://developer.nexmo.com/verify/guides/workflows-and-events
Workflow 6 is absent from `VerifyRequest.Workflow` Class. How do I implement that using nexmo java sdk?

**Comment by lornajane** [comment] 2019-12-23 12:49
This is a duplicate of https://github.com/Nexmo/nexmo-java/issues/275 and workflow 6 can now be added since release 5.2.1 of the Java lib.

**Closed by lornajane** 2019-12-23 12:49 UTC
